#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: R
# autospec version: v21
# autospec commit: f4a13a5
#
Name     : R-ClustVarLV
Version  : 2.1.1
Release  : 56
URL      : https://cran.r-project.org/src/contrib/ClustVarLV_2.1.1.tar.gz
Source0  : https://cran.r-project.org/src/contrib/ClustVarLV_2.1.1.tar.gz
Summary  : Clustering of Variables Around Latent Variables
Group    : Development/Tools
License  : GPL-3.0
Requires: R-ClustVarLV-lib = %{version}-%{release}
Requires: R-Rcpp
Requires: R-RcppEigen
Requires: R-doParallel
Requires: R-foreach
Requires: R-iterators
Requires: R-plyr
BuildRequires : R-Rcpp
BuildRequires : R-RcppEigen
BuildRequires : R-doParallel
BuildRequires : R-foreach
BuildRequires : R-iterators
BuildRequires : R-plyr
BuildRequires : buildreq-R
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
No detailed description available

%package lib
Summary: lib components for the R-ClustVarLV package.
Group: Libraries

%description lib
lib components for the R-ClustVarLV package.


%prep
%setup -q -n ClustVarLV
pushd ..
cp -a ClustVarLV buildavx2
popd
pushd ..
cp -a ClustVarLV buildavx512
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1737137007

%install
export SOURCE_DATE_EPOCH=1737137007
rm -rf %{buildroot}
LANG=C.UTF-8
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -flto -fno-semantic-interposition "
FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -flto -fno-semantic-interposition "
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -flto -fno-semantic-interposition "
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -flto -fno-semantic-interposition "
AR=gcc-ar
RANLIB=gcc-ranlib
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS  -Wl,-z -Wl,relro"
mkdir -p %{buildroot}/usr/lib64/R/library
mkdir -p %{buildroot}-v3/usr/lib64/R/library
mkdir -p %{buildroot}-v4/usr/lib64/R/library
mkdir -p %{buildroot}-va/usr/lib64/R/library

mkdir -p ~/.R
echo "CFLAGS = $CFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper" > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
R CMD INSTALL  --install-tests --use-LTO --built-timestamp=${SOURCE_DATE_EPOCH} --data-compress=none --compress=none --build  -l %{buildroot}-v3/usr/lib64/R/library .
echo "CFLAGS = $CFLAGS -march=x86-64-v4 -mprefer-vector-width=512 -ftree-vectorize  -mno-vzeroupper " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=x86-64-v4 -mprefer-vector-width=512 -ftree-vectorize  -mno-vzeroupper " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=x86-64-v4 -mprefer-vector-width=512 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
R CMD INSTALL --preclean  --install-tests --use-LTO --no-test-load --data-compress=none --compress=none --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}-v4/usr/lib64/R/library .
echo "CFLAGS = $CFLAGS -ftree-vectorize " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -ftree-vectorize " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -ftree-vectorize " >> ~/.R/Makevars
R CMD INSTALL --preclean  --use-LTO --install-tests --data-compress=none --compress=none --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library .
%{__rm} -rf %{buildroot}%{_datadir}/R/library/R.css
%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export _R_CHECK_FORCE_SUGGESTS_=false
R CMD check --no-manual --no-examples --no-codoc . || :

/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}
/usr/bin/elf-move.py avx512 %{buildroot}-v4 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)
/usr/lib64/R/library/ClustVarLV/DESCRIPTION
/usr/lib64/R/library/ClustVarLV/INDEX
/usr/lib64/R/library/ClustVarLV/Meta/Rd.rds
/usr/lib64/R/library/ClustVarLV/Meta/data.rds
/usr/lib64/R/library/ClustVarLV/Meta/features.rds
/usr/lib64/R/library/ClustVarLV/Meta/hsearch.rds
/usr/lib64/R/library/ClustVarLV/Meta/links.rds
/usr/lib64/R/library/ClustVarLV/Meta/nsInfo.rds
/usr/lib64/R/library/ClustVarLV/Meta/package.rds
/usr/lib64/R/library/ClustVarLV/Meta/vignette.rds
/usr/lib64/R/library/ClustVarLV/NAMESPACE
/usr/lib64/R/library/ClustVarLV/R/ClustVarLV
/usr/lib64/R/library/ClustVarLV/R/ClustVarLV.rdb
/usr/lib64/R/library/ClustVarLV/R/ClustVarLV.rdx
/usr/lib64/R/library/ClustVarLV/data/Rdata.rdb
/usr/lib64/R/library/ClustVarLV/data/Rdata.rds
/usr/lib64/R/library/ClustVarLV/data/Rdata.rdx
/usr/lib64/R/library/ClustVarLV/doc/Getting_started_with_ClustVarLV.R
/usr/lib64/R/library/ClustVarLV/doc/Getting_started_with_ClustVarLV.Rmd
/usr/lib64/R/library/ClustVarLV/doc/Getting_started_with_ClustVarLV.html
/usr/lib64/R/library/ClustVarLV/doc/clv3w-vignette.R
/usr/lib64/R/library/ClustVarLV/doc/clv3w-vignette.Rmd
/usr/lib64/R/library/ClustVarLV/doc/clv3w-vignette.html
/usr/lib64/R/library/ClustVarLV/doc/index.html
/usr/lib64/R/library/ClustVarLV/help/AnIndex
/usr/lib64/R/library/ClustVarLV/help/ClustVarLV.rdb
/usr/lib64/R/library/ClustVarLV/help/ClustVarLV.rdx
/usr/lib64/R/library/ClustVarLV/help/aliases.rds
/usr/lib64/R/library/ClustVarLV/help/paths.rds
/usr/lib64/R/library/ClustVarLV/html/00Index.html
/usr/lib64/R/library/ClustVarLV/html/R.css

%files lib
%defattr(-,root,root,-)
/V3/usr/lib64/R/library/ClustVarLV/libs/ClustVarLV.so
/V4/usr/lib64/R/library/ClustVarLV/libs/ClustVarLV.so
/usr/lib64/R/library/ClustVarLV/libs/ClustVarLV.so
